Vagrant.configure(2) do |config|

    # php 5.3
#    config.vm.define "php53" do |cfg|
#      cfg.vm.box = "hashicorp/precise64"
#      cfg.vm.synced_folder "/Users/Hashashiyyin/PhpstormProjects/PhpOrient/", "/var/www/PhpOrient/",
#                                group: "www-data", owner: "www-data"
#      cfg.vm.network "forwarded_port", guest: 80, host: 8080
#      cfg.vm.network "forwarded_port", guest: 9000, host: 9001
#      cfg.vm.network "forwarded_port", guest: 2424, host: 3424
#      cfg.vm.provision "shell", path: "run.sh"
#      cfg.vm.provision "shell", inline: "export VAGRANT_HOST=192.168.99.1"
#      cfg.vm.provision "shell", path: "php53.sh"
#    end

    # php 5.5.9
    config.vm.define "php55+" do |cfg|
      cfg.vm.box = "ubuntu/trusty64"
      cfg.vm.synced_folder "/Users/Hashashiyyin/PhpstormProjects/PhpOrient/", "/var/www/PhpOrient/",
                                group: "www-data", owner: "www-data"
      cfg.vm.network "forwarded_port", guest: 80, host: 8080
      cfg.vm.network "forwarded_port", guest: 9000, host: 9001
      cfg.vm.network "forwarded_port", guest: 2424, host: 3424
      cfg.vm.provision "shell", path: "run.sh"
    end

    # php 5.4.45+
    config.vm.define "php54" do |cfg|
      cfg.vm.box = "ubuntu/trusty64"
      cfg.vm.synced_folder "/Users/Hashashiyyin/PhpstormProjects/PhpOrient/", "/var/www/PhpOrient/",
                                group: "www-data", owner: "www-data"
      cfg.vm.network "forwarded_port", guest: 80, host: 8080
      cfg.vm.network "forwarded_port", guest: 9000, host: 9001
      cfg.vm.network "forwarded_port", guest: 2424, host: 3424
      cfg.vm.provision "shell", path: "run.sh"
      cfg.vm.provision "shell", inline: "export VAGRANT_HOST=192.168.99.1"
      cfg.vm.provision "shell", path: "php54.sh", privileged: false
    end

end
